### ISSUE TITLE
Creare homepage delle API

### ISSUE THREAD

**Issue by MicheleGrisafi** [LorenzoGas/aulando.ayy#38]
Andrebbe creata una pagina HTML di homepage per la presentazione dell API di aulando, nella quale vengano illustrate le diverse funzioni con i vari parametri. In alternativa si potrebbe creare un oggetto JSON equivalente

**Comment by LorenzoGas** [comment]
Dato che utilizziamo apiary non é necessario creare una pagina web per l'API
