### ISSUE TITLE
interface

### ISSUE THREAD

**Issue by LorenzoGas** [LorenzoGas/aulando.ayy#6]
Dato un utente che vuole usufruire dei servizi fornire un interfaccia grafica semplice da usare che permetta la comunicazione con il bot.

HTD: accedo al sito web --> mi é fornita un interfaccia web con una chat ben visibile e bottoni per l'interazione con essa --> mi è possibile digitare del testo nello chat, navigare il sito con i vari bottoni --> posso comunicare con il bot e informarmi sul progetto.

**Comment by AlviseSembenico** [comment]
Aggiunte dipendenze esterne
